import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:loah_app/screens/notifications/widgets/notification_card.dart';
import '../../core/services/notification_repository.dart';
import '../../core/theme/app_theme.dart';
import '../../models/app_notification.dart';
import '../../widgets/loah_app_bar_simple.dart';
import '../finances/add_transaction_screen.dart';
import '../finances/budgets_screen.dart';

/// "Loah - Notificações": unified feed of real push notifications
/// stored in Firestore under /users/{userId}/notifications/.
///
/// Notifications are generated by:
///   - [NotificationScheduler] (client-side periodic checks)
///   - Firebase Cloud Functions (server-side triggers & scheduled jobs)
///
/// They arrive on the device via FCM push, and are also persisted
/// so the feed always shows the complete history.
class NotificationsScreen extends StatefulWidget {
  const NotificationsScreen({super.key});

  @override
  State<NotificationsScreen> createState() => _NotificationsScreenState();
}

class _NotificationsScreenState extends State<NotificationsScreen> {
  final NotificationRepository _repository = NotificationRepository();








  Future<void> _openBudgets() async {
    await Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => const BudgetsScreen()),
    );
  }

  /// "Pagar" on a recurring-bill notification: opens the transaction
  /// form so the user confirms the amount/account.
  Future<void> _payRecurring(AppNotification n) async {
    await Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => const AddTransactionScreen()),
    );
    await _repository.markAsRead(n.id);
  }

  /// Dismiss a single notification (marks as read).
  Future<void> _dismiss(AppNotification n) async {
    await _repository.markAsRead(n.id);
    if (mounted) setState(() {});
  }

  /// Clear all notifications (delete them from Firestore).
  Future<void> _clearAll() async {
    await _repository.clearAll();
    if (mounted) setState(() {});
  }

  /// Builds the row of action buttons/tap behavior for one
  /// notification, based on its category.
  ({VoidCallback? onTap, List<Widget> actions}) _behaviorFor(AppNotification n) {
    final colors = context.loahColors;

    switch (n.category) {
      case NotificationCategory.contacts:
        return (
          onTap: null,
          actions: [
            ElevatedButton(
              onPressed: () => _dismiss(n),
              style: ElevatedButton.styleFrom(
                backgroundColor: colors.accentBlue,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                minimumSize: Size.zero,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(100)),
              ),
              child: const Text('Ok', style: TextStyle(fontSize: 12.5)),
            ),
          ],
        );

      case NotificationCategory.tasks:
        return (onTap: () {}, actions: const []);

      case NotificationCategory.goals:
        return (onTap: () {}, actions: const []);

      case NotificationCategory.finance:
        final isRecurringBill = n.id.startsWith('notif_recurring_');
        if (isRecurringBill) {
          return (
            onTap: null,
            actions: [
              ElevatedButton(
                onPressed: () => _payRecurring(n),
                style: ElevatedButton.styleFrom(
                  backgroundColor: colors.negative,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  minimumSize: Size.zero,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(100)),
                ),
                child: const Text('Pagar', style: TextStyle(fontSize: 12.5)),
              ),
            ],
          );
        }
        return (onTap: _openBudgets, actions: const []);

      case NotificationCategory.system:
        return (onTap: null, actions: const []);
    }
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.loahColors;

    return Scaffold(
      appBar: const LoahAppBarSimple(title: 'Notificações'),
      body: SafeArea(
        child: StreamBuilder<QuerySnapshot>(
          stream: _repository.getNotificationsStream(),
          builder: (context, snapshot) {
            if (snapshot.hasError) {
              return Center(
                child: Text(
                  'Erro ao carregar notificações: ${snapshot.error}',
                  style: Theme.of(context).textTheme.bodyMedium,
                ),
              );
            }

            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(child: CircularProgressIndicator());
            }

            final docs = snapshot.data?.docs ?? [];
            if (docs.isEmpty) {
              return Center(
                child: Text(
                  'Nenhuma notificação por aqui — tudo em dia!',
                  style: Theme.of(context).textTheme.bodyMedium,
                ),
              );
            }

            // Convert Firestore docs to AppNotification models
            final all = docs
                .map((doc) => AppNotification.fromFirestore(doc))
                .where((n) => n.timestamp.isBefore(DateTime.now().add(const Duration(days: 1))))
                .toList();

            final now = DateTime.now();
            final recent = all
                .where((n) => now.difference(n.timestamp).inHours < 24)
                .toList();
            final older = all
                .where((n) => now.difference(n.timestamp).inHours >= 24)
                .toList();

            return ListView(
              padding: const EdgeInsets.all(16),
              children: [
                if (recent.isNotEmpty) ...[
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'RECENTES',
                        style: Theme.of(context).textTheme.labelSmall?.copyWith(
                              letterSpacing: 0.6,
                              color: context.textSecondary,
                            ),
                      ),
                      TextButton.icon(
                        onPressed: _clearAll,
                        icon: Icon(Icons.clear_all, size: 16, color: colors.accentBlue),
                        label: Text(
                          'Limpar tudo',
                          style: TextStyle(color: colors.accentBlue, fontSize: 12.5),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 8),
                  for (final n in recent) ...[
                    _buildCard(n),
                    const SizedBox(height: 10),
                  ],
                  const SizedBox(height: 12),
                ],
                if (older.isNotEmpty) ...[
                  Text(
                    'ANTERIORES',
                    style: Theme.of(context).textTheme.labelSmall?.copyWith(
                          letterSpacing: 0.6,
                          color: context.textSecondary,
                        ),
                  ),
                  const SizedBox(height: 8),
                  for (final n in older) ...[
                    _buildCard(n),
                    const SizedBox(height: 10),
                  ],
                ],
              ],
            );
          },
        ),
      ),
    );
  }

  Widget _buildCard(AppNotification n) {
    final behavior = _behaviorFor(n);
    return NotificationCard(notification: n, onTap: behavior.onTap, actions: behavior.actions);
  }
}

