import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:loah_app/screens/notifications/widgets/notification_card.dart';
import '../../core/l10n/app_localizations.dart';
import '../../core/services/contact_service.dart';
import '../../core/services/goal_service.dart';
import '../../core/services/notification_repository.dart';
import '../../core/services/task_service.dart';
import '../../core/theme/app_theme.dart';
import '../../models/app_notification.dart';
import '../../widgets/loah_app_bar_simple.dart';
import '../contacts/contact_detail_screen.dart';
import '../finances/add_transaction_screen.dart';
import '../finances/budgets_screen.dart';
import '../goals/goal_detail_screen.dart';
import '../tasks/task_detail_screen.dart';

/// "Loah - Notificações": unified feed of real push notifications
/// stored in Firestore under /users/{userId}/notifications/.
///
/// Notifications are generated by:
///   - [NotificationScheduler] (client-side periodic checks)
///   - Firebase Cloud Functions (server-side triggers & scheduled jobs)
///
/// They arrive on the device via FCM push, and are also persisted
/// so the feed always shows the complete history.
///
/// NOTA: o title/message de cada notificação é gerado no momento da
/// criação (NotificationScheduler / Cloud Functions) e gravado como
/// texto já pronto no Firestore — não é traduzido aqui neste ecrã.
/// Apenas os textos fixos da interface (filtros, categorias, tempo
/// relativo, diálogos) usam AppLocales.
class NotificationsScreen extends StatefulWidget {
  const NotificationsScreen({super.key});

  @override
  State<NotificationsScreen> createState() => _NotificationsScreenState();
}

class _NotificationsScreenState extends State<NotificationsScreen> {
  final NotificationRepository _repository = NotificationRepository();
  final TaskService _taskService = TaskService();
  final GoalService _goalService = GoalService();
  final ContactService _contactService = ContactService();

  /// Filter state
  NotificationCategory? _selectedCategory;
  bool _showUnreadOnly = false;

  /// Available filter categories
  static const _allCategories = NotificationCategory.values;

  Future<void> _openBudgets() async {
    await Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => const BudgetsScreen()),
    );
  }

  /// "Pagar" on a recurring-bill notification: opens the transaction
  /// form so the user confirms the amount/account.
  Future<void> _payRecurring(AppNotification n) async {
    await Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => const AddTransactionScreen()),
    );
    await _repository.markAsRead(n.id);
  }

  /// Dismiss a single notification (marks as read).
  Future<void> _dismiss(AppNotification n) async {
    await _repository.markAsRead(n.id);
    if (mounted) setState(() {});
  }

  /// Clear all notifications (delete them from Firestore).
  Future<void> _clearAll() async {
    final loc = AppLocales.of(context);
    final confirm = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text(loc.translate('notif_limpar_titulo')),
        content: Text(loc.translate('notif_limpar_msg')),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(false),
            child: Text(loc.translate('notif_cancelar')),
          ),
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(true),
            child: Text(loc.translate('notif_limpar_confirmar')),
          ),
        ],
      ),
    );
    if (confirm != true) return;
    await _repository.clearAll();
    if (mounted) setState(() {});
  }

  /// Navigates to the task detail screen.
  Future<void> _openTaskDetail(String taskId) async {
    final task = await _taskService.getTask(taskId);
    if (task == null || !mounted) return;
    await Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => TaskDetailScreen(task: task)),
    );
  }

  /// Navigates to the goal detail screen.
  Future<void> _openGoalDetail(String goalId) async {
    final goal = await _goalService.getGoal(goalId);
    if (goal == null || !mounted) return;
    await Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => GoalDetailScreen(goal: goal)),
    );
  }

  /// Navigates to the contact detail screen.
  Future<void> _openContactDetail(String contactId) async {
    final contact = await _contactService.getContact(contactId);
    if (contact == null || !mounted) return;
    await Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => ContactDetailScreen(contact: contact)),
    );
  }

  /// Marks a notification as read, then optionally executes a callback.
  Future<void> _markAsReadAndThen(AppNotification n, [Future<void> Function()? then]) async {
    await _repository.markAsRead(n.id);
    if (then != null) {
      await then();
    }
    if (mounted) setState(() {});
  }

  /// Returns a human-readable label for each category.
  String _categoryLabel(NotificationCategory cat, AppLocales loc) {
    return switch (cat) {
      NotificationCategory.contacts => loc.translate('notif_cat_contatos'),
      NotificationCategory.tasks => loc.translate('notif_cat_tarefas'),
      NotificationCategory.goals => loc.translate('notif_cat_metas'),
      NotificationCategory.finance => loc.translate('notif_cat_financas'),
      NotificationCategory.system => loc.translate('notif_cat_sistema'),
    };
  }

  /// Builds the row of action buttons/tap behavior for one
  /// notification, based on its category.
  ({VoidCallback? onTap, List<Widget> actions}) _behaviorFor(AppNotification n) {
    final colors = context.loahColors;
    final loc = AppLocales.of(context);

    switch (n.category) {
      case NotificationCategory.contacts:
        return (
          onTap: () => _markAsReadAndThen(
            n,
            n.relatedId != null
                ? () => _openContactDetail(n.relatedId!)
                : null,
          ),
          actions: [
            ElevatedButton(
              onPressed: () => _dismiss(n),
              style: ElevatedButton.styleFrom(
                backgroundColor: colors.accentBlue,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                minimumSize: Size.zero,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(100)),
              ),
              child: Text(loc.translate('notif_ok'), style: const TextStyle(fontSize: 12.5)),
            ),
          ],
        );

      case NotificationCategory.tasks:
        return (
          onTap: () => _markAsReadAndThen(
            n,
            n.relatedId != null
                ? () => _openTaskDetail(n.relatedId!)
                : null,
          ),
          actions: [],
        );

      case NotificationCategory.goals:
        return (
          onTap: () => _markAsReadAndThen(
            n,
            n.relatedId != null
                ? () => _openGoalDetail(n.relatedId!)
                : null,
          ),
          actions: [],
        );

      case NotificationCategory.finance:
        final isRecurringBill = n.id.startsWith('notif_recurring_');
        if (isRecurringBill) {
          return (
            onTap: () => _markAsReadAndThen(n),
            actions: [
              ElevatedButton(
                onPressed: () => _payRecurring(n),
                style: ElevatedButton.styleFrom(
                  backgroundColor: colors.negative,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  minimumSize: Size.zero,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(100)),
                ),
                child: Text(loc.translate('notif_pagar'), style: const TextStyle(fontSize: 12.5)),
              ),
            ],
          );
        }
        return (
          onTap: () => _markAsReadAndThen(n, _openBudgets),
          actions: [],
        );

      case NotificationCategory.system:
        return (
          onTap: () => _markAsReadAndThen(n),
          actions: [],
        );
    }
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.loahColors;
    final loc = AppLocales.of(context);

    return Scaffold(
      appBar: LoahAppBarSimple(title: loc.translate('notif_titulo')),
      body: SafeArea(
        child: StreamBuilder<QuerySnapshot>(
          stream: _repository.getNotificationsStream(),
          builder: (context, snapshot) {
            if (snapshot.hasError) {
              return Center(
                child: Text(
                  '${loc.translate('notif_erro_carregar')}${snapshot.error}',
                  style: Theme.of(context).textTheme.bodyMedium,
                ),
              );
            }

            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(child: CircularProgressIndicator());
            }

            final docs = snapshot.data?.docs ?? [];
            if (docs.isEmpty) {
              return Center(
                child: Text(
                  loc.translate('notif_vazio'),
                  style: Theme.of(context).textTheme.bodyMedium,
                ),
              );
            }

            // Convert Firestore docs to AppNotification models
            final all = docs
                .map((doc) => AppNotification.fromFirestore(doc))
                .where((n) => n.timestamp.isBefore(DateTime.now().add(const Duration(days: 1))))
                .toList();

            // Apply filters
            var filtered = all;
            if (_showUnreadOnly) {
              filtered = filtered.where((n) => !n.isRead).toList();
            }
            if (_selectedCategory != null) {
              filtered = filtered.where((n) => n.category == _selectedCategory).toList();
            }

            final now = DateTime.now();
            final recent = filtered
                .where((n) => now.difference(n.timestamp).inHours < 24)
                .toList();
            final older = filtered
                .where((n) => now.difference(n.timestamp).inHours >= 24)
                .toList();

            final hasUnread = all.any((n) => !n.isRead);

            return Column(
              children: [
                // ── Filter chips ──────────────────────────────────
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  child: SingleChildScrollView(
                    scrollDirection: Axis.horizontal,
                    child: Row(
                      children: [
                        _FilterChip(
                          label: loc.translate('notif_todas'),
                          selected: !_showUnreadOnly && _selectedCategory == null,
                          onTap: () => setState(() {
                            _showUnreadOnly = false;
                            _selectedCategory = null;
                          }),
                        ),
                        const SizedBox(width: 8),
                        _FilterChip(
                          label: loc.translate('notif_nao_lidas'),
                          selected: _showUnreadOnly && _selectedCategory == null,
                          count: all.where((n) => !n.isRead).length,
                          onTap: () => setState(() {
                            _showUnreadOnly = true;
                            _selectedCategory = null;
                          }),
                        ),
                        const SizedBox(width: 8),
                        for (final cat in _allCategories) ...[
                          _FilterChip(
                            label: _categoryLabel(cat, loc),
                            selected: _selectedCategory == cat && !_showUnreadOnly,
                            onTap: () => setState(() {
                              _selectedCategory = cat;
                              _showUnreadOnly = false;
                            }),
                          ),
                          const SizedBox(width: 8),
                        ],
                      ],
                    ),
                  ),
                ),
                // ── Notifications list ────────────────────────────
                Expanded(
                  child: filtered.isEmpty
                      ? Center(
                          child: Padding(
                            padding: const EdgeInsets.all(32),
                            child: Text(
                              _showUnreadOnly
                                  ? loc.translate('notif_vazio_nao_lidas')
                                  : loc.translate('notif_vazio'),
                              textAlign: TextAlign.center,
                              style: Theme.of(context).textTheme.bodyMedium,
                            ),
                          ),
                        )
                      : ListView(
                          padding: const EdgeInsets.all(16),
                          children: [
                            if (recent.isNotEmpty) ...[
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text(
                                    loc.translate('notif_recentes'),
                                    style: Theme.of(context).textTheme.labelSmall?.copyWith(
                                          letterSpacing: 0.6,
                                          color: context.textSecondary,
                                        ),
                                  ),
                                  if (hasUnread)
                                    TextButton.icon(
                                      onPressed: _clearAll,
                                      icon: Icon(Icons.clear_all, size: 16, color: colors.accentBlue),
                                      label: Text(
                                        loc.translate('notif_limpar_tudo'),
                                        style: TextStyle(color: colors.accentBlue, fontSize: 12.5),
                                      ),
                                    ),
                                ],
                              ),
                              const SizedBox(height: 8),
                              for (final n in recent) ...[
                                _buildCard(n),
                                const SizedBox(height: 10),
                              ],
                              const SizedBox(height: 12),
                            ],
                            if (older.isNotEmpty) ...[
                              Text(
                                loc.translate('notif_anteriores'),
                                style: Theme.of(context).textTheme.labelSmall?.copyWith(
                                      letterSpacing: 0.6,
                                      color: context.textSecondary,
                                    ),
                              ),
                              const SizedBox(height: 8),
                              for (final n in older) ...[
                                _buildCard(n),
                                const SizedBox(height: 10),
                              ],
                            ],
                          ],
                        ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }

  Widget _buildCard(AppNotification n) {
    final behavior = _behaviorFor(n);
    return NotificationCard(notification: n, onTap: behavior.onTap, actions: behavior.actions);
  }
}

/// A small clickable chip used for filtering notifications.
class _FilterChip extends StatelessWidget {
  final String label;
  final bool selected;
  final int? count;
  final VoidCallback onTap;

  const _FilterChip({
    required this.label,
    required this.selected,
    this.count,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final colors = context.loahColors;
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
        decoration: BoxDecoration(
          color: selected ? colors.accentBlue : colors.cardBackground,
          borderRadius: BorderRadius.circular(100),
          border: Border.all(
            color: selected ? colors.accentBlue : colors.border,
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              label,
              style: TextStyle(
                color: selected ? Colors.white : context.textSecondary,
                fontWeight: FontWeight.w600,
                fontSize: 12.5,
              ),
            ),
            if (count != null && count! > 0) ...[
              const SizedBox(width: 6),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 1),
                decoration: BoxDecoration(
                  color: selected ? Colors.white.withValues(alpha: 0.25) : colors.accentBlue.withValues(alpha: 0.2),
                  borderRadius: BorderRadius.circular(100),
                ),
                child: Text(
                  '$count',
                  style: TextStyle(
                    color: selected ? Colors.white : colors.accentBlue,
                    fontSize: 10,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}