// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuK1TdrHJhGxLhXa7gQPrn7DXG7CRhgko',
    appId: '1:475079305382:web:6c87c6864789aedec22c67',
    messagingSenderId: '475079305382',
    projectId: 'loahapp',
    authDomain: 'loahapp.firebaseapp.com',
    storageBucket: 'loahapp.firebasestorage.app',
    measurementId: 'G-J4HM5MCFVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPN6DupgR7U4utriCeK-wognVEx28YGV4',
    appId: '1:475079305382:android:7d59765359c740bbc22c67',
    messagingSenderId: '475079305382',
    projectId: 'loahapp',
    storageBucket: 'loahapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG7tYGeQzDMJoQZ2jzkhgndq71RWi1PEs',
    appId: '1:475079305382:ios:794a2f519111b759c22c67',
    messagingSenderId: '475079305382',
    projectId: 'loahapp',
    storageBucket: 'loahapp.firebasestorage.app',
    iosBundleId: 'com.portifolio.linozeferino.loahapp',
  );
}
